<?php
namespace geral;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-10-29 at 15:18:13.
 */
class PessoaBOTest extends \PHPUnit_Framework_TestCase {


    /**
     * @covers geral\PessoaBO::getPessoaMaisVelha
     * @todo   Implement testGetPessoaMaisVelha().
     */
    public function testGetPessoaMaisVelha() {
        $stubDAO = $this->getMockBuilder('\geral\PessoaDAO')
                        ->getMock();
        $listaFake = array();
        $listaFake[] = new Pessoa("ADB", 5);
        $listaFake[] = new Pessoa("BASD", 9);
        $stubDAO->method('getTodasAsPessoas')
                ->will($this->returnValue($listaFake));
        $bo = new PessoaBO($stubDAO);
        $this->assertEquals("BASD", $bo->getPessoaMaisVelha()->getNome());
    }
    
    /**
     * @covers geral\PessoaBO::getMaisNovo
     * @todo   Implement testGetMaisNovo().
     */
    public function testGetMaisNovo() {
        $dummyDAO = $this->getMockBuilder('\geral\PessoaDAO')
                         ->getMock();
        $bo = new PessoaBO($dummyDAO);
        $p1 = new Pessoa("ADB", 5);
        $p2 = new Pessoa("BASD", 9);
        $this->assertEquals($bo->getMaisNovo($p1, $p2), $p1);
    }

}
